### PR TITLE
Bugfix/referenced classes

### LINKED ISSUE #35: Classes in method arguments are not put into extension jar
## Expected behavior
A class that is used in as a method parameter should also be put into the extension jar.
The causes the extension to throw a ClassNotFoundException.

## Actual behavior
The class is missing.

### Reproducer code

```
public class MyExtension implements ExtensionMain {

    @Override
    public void extensionStart(
           final @NotNull ExtensionStartInput extensionStartInput, 
           final @NotNull ExtensionStartOutput extensionStartOutput) {
                   doNothing(new B());
    }

    private void doNothing(final @NotNull A a) {

    }
}

public class B extends A {
}

public class A {
}
````

throws:

```
Caused by: java.lang.ClassNotFoundException: A
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.hivemq.extensions.classloader.IsolatedPluginClassloader.loadClass(IsolatedPluginClassloader.java:123)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

## Details
- Affected HiveMQ Testcontainer version(s): 1.0.0

### PR DESCRIPTION
**Pull request by YannickWeber**
Fixed a bug that caused Classes from Method arguments to not be put into the extension jar. 

Resolves #35

### CODE REVIEW

File: core/src/main/java/com/hivemq/testcontainer/core/HiveMQTestContainerCore.java [hunk 1]
```diff
@@ -239,9 +239,8 @@ private void putSubclassesIntoJar(
             final @NotNull JavaArchive javaArchive) throws NotFoundException {
 
         if (clazz != null) {
-            final Set<String> subClassNames =
-                    ClassPool.getDefault().get(clazz.getName()).getClassFile().getConstPool().getClassNames();
-            for (final String subClassName : subClassNames) {
+            final Collection<String> refClasses = ClassPool.getDefault().get(clazz.getName()).getRefClasses();
+            for (final String subClassName : refClasses) {
```
Comment (SgtSilvio) [inline core/src/main/java/com/hivemq/testcontainer/core/HiveMQTestContainerCore.java:243]:
```suggestion
            for (final String refClass : refClasses) {
```
